// Part of ImGui Bundle - MIT License - Copyright (c) 2022-2024 Pascal Thomet - https://github.com/pthom/imgui_bundle
#include <nanobind/nanobind.h>

namespace nb = nanobind;

void nanobind_imgui_part1(nb::module_& m);
void nanobind_imgui_part2(nb::module_& m);
void nanobind_imgui_part3(nb::module_& m);
void nanobind_imgui_part4(nb::module_& m);

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// <litgen_glue_code>  // Autogenerated code below! Do not edit!

// </litgen_glue_code> // Autogenerated code end
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


NB_MODULE(_nanobind_imgui, m)
{
#ifdef STUDY_BUILD_PARTS_PART1
    nanobind_imgui_part1(m);
#endif
#ifdef STUDY_BUILD_PARTS_PART2
    nanobind_imgui_part2(m);
#endif
#ifdef STUDY_BUILD_PARTS_PART3
    nanobind_imgui_part3(m);
#endif
#ifdef STUDY_BUILD_PARTS_PART4
    nanobind_imgui_part4(m);
#endif
}
