name: "Pip"

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build:
    name: Pip
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v5
        with:
          python-version: 3.13

      #    - name: Setup interactive tmate session
      #      uses: mxschmitt/action-tmate@v3

      - name: Build and install
        shell: bash
        run: |
          python --version
          python -m venv .venv
          source .venv/bin/activate
          export STUDY_PYBIND11=ON
          pip install --verbose .

